# Person-Centered Measurement Framework {#measure}

If the entire system of services and supports is intended to be person-centered, its performance should be measured within a framework that also person-centered.  Many existing quality measures and data collection systems were not developed with this in mind. Thus, it will be important to develop a larger framework within which existing measures can be situated.  This allows the system to retain the quality measurement work that has been completed, while filling gaps that may lead to inconsistency and poor quality.

<!-- What does existing quality measures and data collection systems currently address or focus on? Be sure to identify what is lacking… -->

The framework outlined here attempts to align with and fulfill the promise of current definitions of person-centered planning, as well as with existing and evolving standards in the fields of behavioral health and developmental disability services.  Far from contradicting these standards, it attempts to provide a broader, person-centered context for the development of the system as a whole.

Ongoing work in this area would include:

- Developing a person-centered measurement framework 
- Conducting an inventory of available data assets at a state wide level
- Classifying existing measurement and data collection efforts (e.g. HEDIS, BH-TEDS, etc.) within the context of this framework
- Gap analysis of current datasets and development of a plan to address measurement gaps.

## What do we mean by 'a better life'?

People have been asking themselves what it means to live a good life for thousands of years,^[The philosopher Aristotle defined the highest good of human life as happiness, or flourishing (*eudaimonia*).  cf. *Nicomachean Ethics*] and it is among the most crucial questions for each of us to answer.  For the purpose of this measurement framework, we will refer to the characteristics that make up a good life as *quality of life*, or QOL for short, relying primarily on contemporary research to arrive at a common and usable definition.

### What makes a good definition?

If we are going to try to define quality of life, it is important that our definition gets a few things right:^[These considerations are drawn from [Cummins, R. (2005). Moving from the quality of life concept to a theory. JIDR, 49(10), 699-706](https://www.ncbi.nlm.nih.gov/pubmed/16162114).]

1. *Multiple dimensions*.  A good life can only be described using multiple dimensions. These are influenced by personal factors, environmental factors, and the interaction between those factors.
2. *Broad enough for everyone*.  We should each want to apply the definition to our own lives.  The basic characteristics of a good life are the same for all people, regardless of culture, gender, disability, etc. 
3. *Both subjective and objective*. People have different priorities.  While a definition can point to objective facts related to QoL, it must include the point-of-view of the person who is living their life from day to day.  Each dimension of a QoL model may have both objectively and subjectively defined indicators.

Taken together, the criteria listed above seek to balance the abstract with the specific and to arrive at a definition which is well-rounded while also being understandable.

### What makes a better life? 

Keeping our key requirements in mind, we can draw from the broad reservoir of studies on QoL to find frameworks which are multi-dimensional^[See systematic review of HRQoL recommending addition of individual and environmental characteristics:  [Bakas, T., et al. (2012)](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3548743/).], cross-culturally relevant,^[See [Schalock, R., et al. (2005).](https://www.researchgate.net/profile/Mian_Wang4/publication/7801771_Cross-Cultural_Study_of_Quality_of_Life_Indicators/links/0deec52df448eac34d000000/Cross-Cultural-Study-of-Quality-of-Life-Indicators.pdf).] and which provide both subjective and objective indicators.

Below is a potential model listing essential dimensions of QoL:

```{r echo=FALSE, message=FALSE, warning=FALSE}

tribble(
  ~Area,                  ~Dimension,                ~`Example Indicators`,
  #--|--|----
  "Independence",         "Personal development",    "Education status, personal skills, ADLs, IADLs",
  "            ",         "Self-determination",      "Choices, autonomy, personal control, goals",
  "Social participation", "Interpersonal relations", "Social networks, activities, relationships",
  "                    ", "Social inclusion",        "Community integration, participation, roles",
  "                    ", "Rights",                  "Human (respect/dignity, equality), Legal",
  "Well-being",           "Emotional well-being",    "Safety, positive experiences, self-concept, stress",
  "          ",           "Physical well-being",     "Health, nutrition, recreation/physical exertion",
  "          ",           "Material well-being",     "Financial status, employment, housing, possessions"
) %>%
knitr::kable(caption = 'QoL Dimensions')

```

Please note that the framework listed above is one of many potential models, each of which contains many of the same basic dimensions, and many were developed with populations having specific conditions.  Some other broad-based models for review include:

- The [World Health Organization Quality of Life (WHOQOL)](https://apps.who.int/iris/bitstream/handle/10665/77932/WHO_HIS_HSI_Rev.2012.03_eng.pdf?sequence=1&isAllowed=y) domains.
- The [Eurostat QoL indicators](https://ec.europa.eu/eurostat/statistics-explained/index.php?title=Quality_of_life_indicators) show an example of QoL domains applied for entire countries alongside financial indicators such as gross domestic product (GDP).
- Healthy People 2020 has selected a subset of measures for monitoring health-related QoL and well-being in the United States.  See their [Foundation Health Measure Report: Health-Related QoL and Well-Being](https://www.healthypeople.gov/sites/default/files/HRQoLWBFullReport.pdf).

## Benefits of a QoL Perspective

### What other frameworks exist?

One might well ask: *Is quality of life the only potential framework that we could use to measure improvement?*  The answer is *No*, so it is worth discussing other options and briefly reviewing the attributes of each.  Other options include:

- *Symptom reduction*: Measurement of reduction in symptoms related to specific diagnosable conditions.  Symptom scales such as the [PHQ-9](https://www.phqscreeners.com/sites/g/files/g10049256/f/201412/PHQ-9_English.pdf), [GAD-7]() and other tools have commonly been used to measure the impact of treatments on specific conditions, but they are more challenging to use for people with multiple co-occuring conditions (MCC).
- *Improving functional status*: Most currently used assessment tools address functional status, measuring the impact of various conditions on broader life areas in terms of their impact on functional ability.  These are broader than symptom scales, and can detect the impact of various symptoms on a particular functional domain.
- *Health-related quality of life (HRQoL)*:  HRQoL addresses a subset of QoL domains which are related to perceived physical and mental health.  These models typically exclude non-medical areas such as education or rights, focusing on physical domains like 'mobility'. 

### Why is a quality of life framework better than others?

A QoL approach has the following benefits over the approaches mentioned above:

**Strengths-based**:  A QoL approach asks people what they want their lives to be and encourages them to work toward that vision.  Rather than focusing on needs or deficits, it aspires to use a person's strengths to improve his or her life.^[See the MDHHS PCP Policy value that "The PCP approach identifies the person’s strengths, goals, choices... and desired outcomes." (p. 4)]

**Inclusive**: Instruments and measures from each of the other areas can be used as a part of the QoL framework, since it is broad enough to include each of these areas, and they each contribute to it.  A QoL approach does not neglect the value of functional gains or symptom reduction, but values these as contributors to overall quality of life.  For instance, if a person experiences an alleviation of their depressive symptoms using the PHQ-9, this would be seen as contributing toward the individual's QoL in the area of 'Emotional Well-being'.

**Contextual**: An approach which focuses on only a portion of an individual's life, such as mobility or anxiety symptoms, is likely to miss out on the bigger picture.  It may also inadvertently create siloes among the individuals supporting the person.  For instance, more recent evaluations have criticized the HRQoL approach as failing to "sufficient emphasis on mental and social domains...that are essential to people."^[Read [Pietersma, S., et al. (2013)](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4031380/) regarding domains of quality of life.]  The broader focus on QoL which is proposed here is aligned with our evolving understanding of several areas, each of which stresses the critical relationship between each of us and our communities and surroundings:

- *Social Determinants of Health* (SDoH): A vast and growing body of [research](https://www.cdc.gov/socialdeterminants/research/index.htm) indicates that the places and conditions in which we live are intrinsically tied to the quality of our lives and the likelihood of achieving positive outcomes from the supports and services we receive. 
- *Trauma-Informed Care*: More and more models for service provision, informed by research and by the lived experience of trauma survivors, are founded on the recognition that adverse events in our relationships and in our lived environment can have a profound and lifelong impact on our lives.^[For a recent review of these models, see: [Purtle, J. (2018). Trauma, Violence, & Abuse](https://www.ncbi.nlm.nih.gov/pubmed/30079827).]
- *Supports Paradigm*: A model, prevalent in the IDD supports system, that views a person's functioning as the match between their individual capacity and the environment in which they are expected to live and work.^[See [Thompson, et al. (2009)](https://www.ncbi.nlm.nih.gov/pubmed/19368481) on conceptualizing support needs.]  In this model, supports are viewed as a way to supplement the persons strengths and to help match those to the person's environment.



