--- 
title: "A Person-Centered Framework"
author: "Various authors"
date: "`r Sys.Date()`"
output:
  word_document: default
  pdf_document: default
description: A working document outlining the process, sources, and formation of a comprehensive body of knowledge for person-centered planning.
documentclass: book
link-citations: yes
bibliography:
- book.bib
- packages.bib
site: bookdown::bookdown_site
biblio-style: apalike
---

# Reason

Each person's ability to choose a better future and map their journey toward it: this is what person-centered planning enables.  In order for services to effectively support a person in this process, they must be provided within the context of a person's goals. Orienting a broad and complex system to keep the person at the center requires a consistent, overarching framework.  MDHHS BHDDA is working to support this person-centered orientation with the following strategy:

**Goal:** To develop [a common body of knowledge](#bok) for person-centered planning,
mapped to [relevant policies](#policy) and [research](#research),
which will inform a [shared curriculum](#curriculum)
and [measurement framework](#measure)
to support [improved quality of life](#pcpdca) for each person.

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
