# concepts.R

library(tidyverse)

# Group terms to concepts

vocab <- read_csv("data/reg_vocab.csv")
dtm_sections <- read_csv("data/reg_dtm_sections.csv")
corpus_sections <- read_csv("data/reg_corpus_sections.csv")
reg_list <- read_csv("data/reg_list.csv")

concepts <-
  vocab %>%
  mutate(
    concept = case_when(
      str_detect(term,"person_centered$")  ~ "person_centered_practice",
      str_detect(term,"patient_centered$") ~ "person_centered_practice",
      str_detect(term,"individual_centered$") ~ "person_centered_practice",
      str_detect(term,"person_centered_family_centered$") ~ "person_centered_practice",
      str_detect(term,"centered_planning") ~ "pcp_process",
      str_detect(term,"discharge_planning")~ "pcp_process",
      str_detect(term,"transition_planning") ~ "pcp_process",
      str_detect(term,"care_planning")     ~ "pcp_process",
      str_detect(term,"developing_plan_of_care") ~ "pcp_process",
      str_detect(term,"developing_ipos") ~ "pcp_process",
      str_detect(term,"preparation_of_treatment_plan") ~ "pcp_process",
      str_detect(term,"development_of_treatment_plan") ~ "pcp_process",
      str_detect(term,"recovery_planning") ~ "pcp_process",
      str_detect(term,"discharge_planning")~ "pcp_process",
      str_detect(term,"treatment_planning")~ "pcp_process",
      str_detect(term,"planning_process")  ~ "pcp_process",
      str_detect(term,"family_planning$")  ~ "pcp_process",
      str_detect(term,"design_unique_path") ~ "pcp_process",
      str_detect(term,"independent_facilitat") ~ "independent_facilitation",
      str_detect(term,"pre_planning")      ~ "pre_planning",
      str_detect(term,"pcp_meeting")       ~ "pcp_meeting",
      str_detect(term,"person_centered_planning_meeting")       ~ "pcp_meeting",
      str_detect(term,"implementing_plan_of_care") ~ "implement_plan",
      str_detect(term,"plan_implementation") ~ "implement_plan",
      str_detect(term,"patient_specific_education") ~ "train_plan",
      str_detect(term,"patient_education_training") ~ "train_plan",
      str_detect(term,"education_medications_provided_patient") ~ "train_plan",
      str_detect(term,"family_education")  ~ "train_plan",
      str_detect(term,"caregiver_education") ~ "train_plan",
      str_detect(term,"education_treatment") ~ "train_plan",
      str_detect(term,"parent_education")  ~ "train_plan",
      str_detect(term,"provider_education") ~ "train_plan",
      str_detect(term,"changes_plan_of_care") ~ "adjust_plan",
      str_detect(term,"revised_plan_of_care") ~ "adjust_plan",
      str_detect(term,"treatment_goal")    ~ "goals_objectives",
      str_detect(term,"individual_objective") ~ "goals_objectives",
      str_detect(term,"patient_outcome")   ~ "goals_objectives",
      str_detect(term,"outcomes_patients") ~ "goals_objectives",
      str_detect(term,"care_outcome")      ~ "goals_objectives",
      str_detect(term,"therapeutic_outcome") ~ "goals_objectives",
      str_detect(term,"clinical_outcome")  ~ "goals_objectives",
      str_detect(term,"health_outcome")    ~ "goals_objectives",
      str_detect(term,"desired_outcomes")  ~ "goals_objectives",
      str_detect(term,"improved_health")   ~ "goals_objectives",
      str_detect(term,"^hopes")            ~ "goals_objectives",
      str_detect(term,"dream")             ~ "goals_objectives",
      str_detect(term,"care_goals")        ~ "goals_objectives",
      str_detect(term,"individual’s_goals") ~ "goals_objectives",
      str_detect(term,"care_outcomes")     ~ "goals_objectives",
      str_detect(term,"goals_preferences") ~ "goals_objectives",
      str_detect(term,"goals_of_care")     ~ "goals_objectives",
      str_detect(term,"patient's_goals")   ~ "goals_objectives",
      str_detect(term,"family_goals")      ~ "goals_objectives",
      str_detect(term,"individual_outcomes") ~ "goals_objectives",
      str_detect(term,"employment_outcomes") ~ "goals_objectives",
      str_detect(term,"behavioral_plan|behavior_treatment_plan") ~ "behavior_treatment_plan",
      str_detect(term,"plan_of_service")   ~ "plan_of_service",
      str_detect(term,"plan_of_care")      ~ "plan_of_service",
      str_detect(term,"service_plan")      ~ "plan_of_service",
      str_detect(term,"ipos_|_ipos|^ipos$") ~ "plan_of_service",
      str_detect(term,"recovery_plan")     ~ "plan_of_service",
      str_detect(term,"individual_plan")   ~ "plan_of_service",
      str_detect(term,"specific_care_plan") ~ "plan_of_service",
      str_detect(term,"copy_of_care_plan") ~ "plan_of_service",
      str_detect(term,"services_care_plan") ~ "plan_of_service",
      str_detect(term,"comprehensive_care_plan") ~ "plan_of_service",
      str_detect(term,"individualized_care_plan") ~ "plan_of_service",
      str_detect(term,"advance_care_plan") ~ "plan_of_service",
      str_detect(term,"_poc$|^poc$|^poc_") ~ "plan_of_service",
      str_detect(term,"care_plan_field")   ~ "plan_of_service",
      str_detect(term,"nursing_care_plan") ~ "treatment_plan",
      str_detect(term,"therapy_plan")      ~ "treatment_plan",
      str_detect(term,"treatment_plan$|treatment_plan_") ~ "treatment_plan",
      str_detect(term,"written_plan_of_treatment") ~ "treatment_plan",
      str_detect(term,"crisis_plan")       ~ "crisis_plan",
      str_detect(term,"safety_plan")       ~ "crisis_plan",
      str_detect(term,"discharge_plan")    ~ "discharge_plan",
      str_detect(term,"plan_of_discharge") ~ "discharge_plan",
      str_detect(term,"advance_directive") ~ "advance_directive",
      str_detect(term,"periodic_reviews")  ~ "periodic_review",
      str_detect(term,"review_ipos")       ~ "periodic_review",
      str_detect(term,"annual_resident_review")  ~ "periodic_review",
      str_detect(term,"self_determin")     ~ "self_determination",
      str_detect(term,"self_direct")       ~ "self_directed",
      str_detect(term,"individual_directs") ~ "self_directed",
      str_detect(term,"individual_budget") ~ "self_directed",
      str_detect(term,"individual’s_budget") ~ "self_directed",
      str_detect(term,"self_administ")     ~ "self_management",
      str_detect(term,"self_manage")       ~ "self_management",
      str_detect(term,"self_care")         ~ "self_management",
      str_detect(term,"compliance_treatment") ~ "self_management",
      str_detect(term,"individual_choice") ~ "decision_making",
      str_detect(term,"informed_choice")   ~ "decision_making",
      str_detect(term,"of_choice")         ~ "decision_making",
      str_detect(term,"informed_decision") ~ "decision_making",
      str_detect(term,"shared_decision")   ~ "decision_making",
      str_detect(term,"informed_decision") ~ "decision_making",
      str_detect(term,"decision_making_counseling_coordination") ~ "decision_making",
      str_detect(term,"right_choose")      ~ "decision_making",
      str_detect(term,"individual_choose") ~ "decision_making",
      str_detect(term,"treatment_option")  ~ "decision_making",
      str_detect(term,"free_choice")       ~ "decision_making",
      str_detect(term,"alternative_treatment") ~ "decision_making",
      str_detect(term,"alternative_care")  ~ "decision_making",
      str_detect(term,"alternative_services") ~ "decision_making",
      str_detect(term,"alternative_inpatient") ~ "decision_making",
      str_detect(term,"care_decisions")    ~ "decision_making",
      str_detect(term,"decisions_treatment") ~ "decision_making",
      str_detect(term,"individual_approved") ~ "decision_making",
      str_detect(term,"individual_chosen") ~ "decision_making",
      str_detect(term,"assessment")        ~ "assessment",
      str_detect(term,"determine_need")    ~ "assessment",
      str_detect(term,"biopsychosocial")   ~ "assessment",
      str_detect(term,"screening")         ~ "screening",
      str_detect(term,"dignity")            ~ "dignity",
      str_detect(term,"rights")            ~ "dignity",
      str_detect(term,"preference")        ~ "preferences",
      str_detect(term,"strengths")         ~ "strengths",
      str_detect(term,"_abilities")        ~ "strengths",
      str_detect(term,"family_skills")     ~ "strengths",
      str_detect(term,"recovery_skills")   ~ "strengths",
      str_detect(term,"achieved_skills")   ~ "strengths",
      str_detect(term,"social_skills")     ~ "strengths",
      str_detect(term,"coping_skills")     ~ "strengths",
      str_detect(term,"health_safety")     ~ "safety",
      str_detect(term,"health_risk")       ~ "safety",
      str_detect(term,"physical_safety")   ~ "safety",
      str_detect(term,"fall_risk")         ~ "safety",
      str_detect(term,"injury_risk")       ~ "safety",
      str_detect(term,"risk_behaviors")    ~ "safety",
      str_detect(term,"social_risk")       ~ "safety",
      str_detect(term,"patient_significant_risk") ~ "safety",
      str_detect(term,"risk_of_death")     ~ "safety",
      str_detect(term,"patient_risk")      ~ "safety",
      str_detect(term,"serious_risk")      ~ "safety",
      str_detect(term,"suicide_risk")      ~ "safety",
      str_detect(term,"immediate_risk")    ~ "safety",
      str_detect(term,"harm_risk")         ~ "safety",
      str_detect(term,"readmission_risk")     ~ "safety",
      str_detect(term,"individual_requires") ~ "needs",
      str_detect(term,"condition_requires") ~ "needs",
      str_detect(term,"patient_requires")  ~ "needs",
      str_detect(term,"resident_requires") ~ "needs",
      str_detect(term,"beneficiary_requires") ~ "needs",
      str_detect(term,"patient.*need")     ~ "needs",
      str_detect(term,"functional_need")   ~ "needs",
      str_detect(term,"treatment_need")    ~ "needs",
      str_detect(term,"health_need")       ~ "needs",
      str_detect(term,"resources_needed")  ~ "needs",
      str_detect(term,"needs_identified")  ~ "needs",
      str_detect(term,"individual.*need")  ~ "needs",
      str_detect(term,"address_needs")     ~ "needs",
      str_detect(term,"needs_of_individual") ~ "needs",
      str_detect(term,"patient_needs")     ~ "needs",
      str_detect(term,"support_needs")     ~ "needs",
      str_detect(term,"need_treatment")    ~ "needs",
      str_detect(term,"resident.*needs")   ~ "needs",
      str_detect(term,"medical_need")      ~ "needs",
      str_detect(term,"care_need")         ~ "needs",
      str_detect(term,"symptom")           ~ "needs",
      str_detect(term,"medical_necessity") ~ "needs",
      str_detect(term,"health_issues")     ~ "needs",
      str_detect(term,"_disorders")        ~ "needs",
      str_detect(term,"health_condition")  ~ "needs",
      str_detect(term,"impairment|impaired") ~ "needs",
      str_detect(term,"resident_funds")    ~ "personal_finances",
      str_detect(term,"within_community")  ~ "community",
      str_detect(term,"community_members") ~ "community",
      str_detect(term,"community_setting") ~ "community",
      str_detect(term,"community_inclusion") ~ "community",
      str_detect(term,"community_particip") ~ "community",
      str_detect(term,"community_activit") ~ "community",
      str_detect(term,"community_life")    ~ "community",
      str_detect(term,"community_integrat") ~ "community",
      str_detect(term,"local_community")   ~ "community",
      str_detect(term,"community_living")  ~ "community",
      str_detect(term,"community_resource") ~ "community",
      str_detect(term,"neighbors")         ~ "community",
      str_detect(term,"supported_employment") ~ "employment",
      str_detect(term,"community_employment") ~ "employment",
      str_detect(term,"competitive_employment") ~ "employment",
      str_detect(term,"employment_individual") ~ "employment",
      str_detect(term,"employment_work_competitive") ~ "employment",
      str_detect(term,"geographic_area")   ~ "local_area",
      str_detect(term,"prone_areas")       ~ "local_area",
      str_detect(term,"urban_area")        ~ "local_area",
      str_detect(term,"area_urban")        ~ "local_area",
      str_detect(term,"prone_area")        ~ "local_area",
      str_detect(term,"commuting_area")    ~ "local_area",
      str_detect(term,"shortage_area")     ~ "local_area",
      str_detect(term,"areas_within_state") ~ "local_area",
      str_detect(term,"hospitals_area")    ~ "local_area",
      str_detect(term,"area_without_inpatient_hospital") ~ "local_area",
      str_detect(term,"borderland_area")   ~ "local_area",
      str_detect(term,"statistical_area")  ~ "local_area",
      str_detect(term,"disaster_area")     ~ "local_area",
      str_detect(term,"market_area")       ~ "local_area",
      str_detect(term,"nonurbanized_area") ~ "local_area",
      str_detect(term,"local_economies")   ~ "local_area",
      str_detect(term,"reside_area")       ~ "local_area",
      str_detect(term,"tribal_area")       ~ "local_area",
      str_detect(term,"home_area")         ~ "local_area",
      str_detect(term,"underserved_area")  ~ "local_area",
      str_detect(term,"service_area")      ~ "local_area",
      str_detect(term,"family_support")    ~ "natural_supports",
      str_detect(term,"social_support")    ~ "natural_supports",
      str_detect(term,"natural_support")   ~ "natural_supports",
      str_detect(term,"friends")           ~ "natural_supports",
      str_detect(term,"conflict_of_interest") ~ "conflict_free",
      str_detect(term,"care_coordination") ~ "service_coordination",
      str_detect(term,"coordination_care") ~ "service_coordination",
      str_detect(term,"supports_coordination") ~ "service_coordination",
      str_detect(term,"case_management")   ~ "service_coordination",
      str_detect(term,"care_management")   ~ "service_coordination",
      str_detect(term,"coordination_communication") ~ "service_coordination",
      str_detect(term,"coordination_transitions") ~ "service_coordination",
      str_detect(term,"planning_coordination") ~ "service_coordination",
      str_detect(term,"referral_coordination") ~ "service_coordination",
      str_detect(term,"communication_coordination") ~ "service_coordination",
      str_detect(term,"coordination_of_services") ~ "service_coordination",
      str_detect(term,"services_coordination") ~ "service_coordination",
      str_detect(term,"coordination_of_care") ~ "service_coordination",
      str_detect(term,"care_transitions")  ~ "service_coordination",
      str_detect(term,"transitions_care")  ~ "service_coordination",
      str_detect(term,"transitions_of_care") ~ "service_coordination",
      str_detect(term,"transitions_referrals") ~ "service_coordination",
      str_detect(term,"facility_transitions") ~ "service_coordination",
      str_detect(term,"coordination_continuity_of_care") ~ "service_coordination",
      str_detect(term,"care_facilit")      ~ "service_setting",
      str_detect(term,"health_clinic")     ~ "service_setting",
      str_detect(term,"family_planning_clinic") ~ "service_setting",
      str_detect(term,"inpatient_facility") ~ "service_setting",
      str_detect(term,"practitioner")      ~ "service_provider",
      str_detect(term,"provider")          ~ "service_provider",
      str_detect(term,"physician")         ~ "service_provider",
      str_detect(term,"clinician")         ~ "service_provider",
      str_detect(term,"social_worker")     ~ "service_provider",
      str_detect(term,"health_professional") ~ "service_provider",
      str_detect(term,"care_professional") ~ "service_provider",
      str_detect(term,"case_manager")      ~ "service_provider",
      str_detect(term,"supports_coodinator") ~ "service_provider",
      str_detect(term,"npi")               ~ "service_provider",
      str_detect(term,"agency_inpatient")  ~ "service_provider",
      str_detect(term,"inpatient")         ~ "services",
      str_detect(term,"outpatient")        ~ "services",
      str_detect(term,"services")          ~ "services",
      str_detect(term,"service_delivery")  ~ "services",
      str_detect(term,"_supports|supports_") ~ "services",
      str_detect(term,"_treatment")        ~ "services",
      str_detect(term,"patient_encounter") ~ "services",
      str_detect(term,"telehealth")        ~ "services",
      str_detect(term,"^cultur")           ~ "culture",
      str_detect(term,"race_ethnicity")    ~ "culture",
      str_detect(term,"group_of_race")     ~ "culture",
      str_detect(term,"family")            ~ "family",
      str_detect(term,"spouse")            ~ "family",
      str_detect(term,"^parent_|_parent")  ~ "family",
      str_detect(term,"parent'_|_parent's") ~ "family",
      # keep person-related items last, since compound terms should be picked up above first
      str_detect(term,"beneficiary")       ~ "person",
      str_detect(term,"patient")           ~ "person",
      str_detect(term,"individuals")       ~ "person",
      str_detect(term,"individual_receiving") ~ "person",
      str_detect(term,"individuals")       ~ "person",
      str_detect(term,"individual's")      ~ "person",
      str_detect(term,"individual_client") ~ "person",
      str_detect(term,"individual_consumer") ~ "person",
      str_detect(term,"individual_member") ~ "person",
      str_detect(term,"individual_resident") ~ "person",
      str_detect(term,"individual_guardian") ~ "person",
      str_detect(term,"individual_seeking") ~ "person",
      str_detect(term,"individual_receiving") ~ "person",
      str_detect(term,"service_recipient") ~ "person",
      str_detect(term,"recipient's")       ~ "person",
      str_detect(term,"recipient_individual") ~ "person",
      str_detect(term,"recipients")        ~ "person",
      str_detect(term,"person$|person_")   ~ "person",
      TRUE                                 ~ NA_character_
    )
  ) %>%
  as_tibble() 


dtm_concepts <-
  dtm_sections %>%
  inner_join(
    concepts %>% filter(!is.na(concept)) %>% select(term,concept),
    by = c("feature" = "term")
  ) %>%
  group_by(document,concept) %>%
  summarize(n = sum(frequency)) %>%
  ungroup() %>%
  pivot_wider(names_from = concept, values_from = n) %>%
  mutate(has_concept = TRUE)

corpus_concepts <-
  corpus_sections %>%
  select(-text_clean) %>%
  left_join(dtm_concepts, by = c("id" = "document")) %>%
  select(ends_with("id"),section,ends_with("_page"),text,everything())

write_csv(dtm_concepts,"data/dtm_concepts.csv")
write_csv(corpus_concepts,"data/corpus_concepts.csv")
write_csv(concepts,"data/concepts.csv")

# Missing terms

concept_summary <-
  concepts %>%
  filter(!is.na(concept)) %>%
  group_by(concept) %>%
  summarize(
    includes = paste(term,collapse = "; "),
    n_terms = n_distinct(term),
    n = sum(term_count)
  ) %>%
  arrange(desc(n))
